easy_admin:
    site_name: '<b style="font-size: 80%; color: #262424;">LITA</b>'
    entities:
        Academy:
            class: App\Entity\Academy
        City:
            class: App\Entity\City
        Consumer:
            class: App\Entity\Consumer
        Review:
            class: App\Entity\Review
            form:
                fields:
                    - { property: 'review_stars', type: 'choice', type_options:
                        { multiple: false, choices:
                          {
                              '1':  '1',
                              '2':  '2',
                              '3':  '3',
                              '4':  '4',
                              '5':  '5'
                          }
                        }
                      }
                    - review_data
                    - review_comment
                    - program
                    - consumer
        Program:
            class: App\Entity\Program
            form:
                fields:
                - { property: 'program_name', type: 'choice', type_options:
                    { multiple: false, choices:
                        {
                            'Front-End':  'Front-End',
                            'Back-End':   'Back-End',
                            'Testavimas': 'Testavimas'
                        }
                      }
                   }
                - program_url
                - program_price
                - events
                - academy
                - program_description
        ProgramEvent:
            class: App\Entity\ProgramEvent
