# config/packages/security.yaml
security:
  # ...
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email
  firewalls:
    # ...
    main:
      # ...
      guard:
        authenticators:
          - App\Security\GoogleAuthenticator
